# 1. My Lane  and Why

## Selected Lane
I selected **Lane 4: CTR(Clich-Through Rate)**.

## Why I Selected This Lane

I choose this lane because it's a lane that has a lot of impressions but a low number of clicks and a low user engagement. These pages can be used to determine which pages need to be prioritized to be optimized for titles, meta descriptions, content, or user experience.

# 2. The Question

## Research Question

Which pages are visible and not capturing clicks or engagement or should be reviewed as such for metadata, content or monitoring?

## Unit of Analysis

The unit of analysis is **one content page**.

## Decision

The next step is to determine which pages need to be optimized for CTR or engagement.

## Output

The results will be a list of pages that have opportunities for improvement in CTR/Engagement.

## Action

Content teams will be able to analyze page titles, meta descriptions, page structure, content quality, and user experience to boost click-through rates and engagement.

## Cost of a Wrong Recommendation

If the recommendation is wrong, high-performing pages may receive unnecessary changes while pages with real problems could be ignored. This may waste time and reduce the effectiveness of optimization efforts.

## Why Data or Machine Learning Can Help

CTR and engagement are affected by multiple factors such as impressions, average position, page age, content type, sessions, and engagement metrics. Machine learning can analyze these factors together and help prioritize pages more effectively than simple manual rules.

In [ ]:
import pandas as pd

df = pd.read_csv("../../data/raw/content_refresh_anonymized.csv")

df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [ ]:
print("Total Pages:", len(df))
print("Average CTR:", df["ctr"].mean())
print("Average Position:", df["avg_position"].mean())

Total Pages: 30000
Average CTR: 0.5107333333333334
Average Position: 16.342380000000002

# 3. Quick Look at the Data

The starter dataset includes details of the performance of the content such as impressions, clicks, CTR, average position, sessions, and engagement metrics.

The data in the dataset will be used to create a summary of statistics that will give evidence of pages with high visibility and lower click-through rates or engagement. These observations will help in taking the next steps of choosing the CTR and the Engagement Opportunity Scoring lane to be analyzed further.

# 4. Careful Words

This analysis highlights pages that might need additional scrutiny due to the information available.

The findings reveal trends and patterns within the data, but don't guarantee that making a change on a page will directly lead to higher click-through rates or engagement.

Recommendations to be generated by this project should be vetted by a human prior to implementation.

# 5. Self-Check

- ✔ I chose one existing track.
- ✔ I explained the research question.
- ✔ I identified the decision and action.
- ✔ I described the consequences of recommending a wrong step.
- ✔ I will include real numbers from the starter dataset.
- ✔ Used precise language and refrained from unsupported statements.

In [ ]:
import os

print(os.getcwd())

/workspaces/inshrah-flyrank/work/Notebooks

In [ ]:
import os

print(os.path.exists("../../data/raw/content_refresh_anonymized.csv"))

True

In [ ]:
import pandas as pd

df = pd.read_csv("../../data/raw/content_refresh_anonymized.csv")

df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7